In [2]:
import numpy as np
arr = np.array([1,2,3])
print(arr+5)

[6 7 8]


In [4]:
a = np.array([[1],[2],[3]])   # shape (3,1)
b = np.array([10,20,30]) 
print(a)    # shape (3,)
print(b)
print(a + b)

[[1]
 [2]
 [3]]
[10 20 30]
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [6]:
M = np.ones((3,3))
v = np.array([1,2,3])
print(M * v)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [8]:
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
row_mean= M.mean(axis=1,keepdims=True)
normalized= M - row_mean
print("Original:\n", M)
print("Row means:\n", row_mean)
print("Normalized:\n", normalized)

Original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Row means:
 [[2.]
 [5.]
 [8.]]
Normalized:
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [9]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(M[0:2, 1:3]) 

[[2 3]
 [5 6]]


In [15]:
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
n=np.mean(M)
print(M[M>n])
print(M[M%2!=0])
print(M[M%3==0])

[6 7 8 9]
[1 3 5 7 9]
[3 6 9]


In [4]:
a= np.arange(12)
print(a.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]


In [8]:
print(np.hstack((a,b)))

[1 2 3 4 5 6]


In [11]:
a= np.arange(9).reshape(3,3)
print(np.hsplit(a,3))

[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]


In [13]:
print(np.vsplit(a, 3))

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]


In [15]:
arr = a.flatten()
print(arr)

[0 1 2 3 4 5 6 7 8]


In [17]:
r= arr.ravel()
r[0]= 99
r[3]= 10
print(arr)

[99  1  2 10  4  5  6  7  8]


In [21]:
a= np.array([1,2,3])
b= np.array([4,5,6])
print(np.vstack((a,b)))
print(np.shape(np.vstack((a,b))))

[[1 2 3]
 [4 5 6]]
(2, 3)


In [22]:
print(np.hstack((a,b)))

[1 2 3 4 5 6]


In [33]:
a = (np.arange(16)).reshape(4,4)
b=np.vsplit(a,2)
c= np.hsplit(b[0],2)
d=np.hsplit(b[1],2)
print(c,d)

[array([[0, 1],
       [4, 5]]), array([[2, 3],
       [6, 7]])] [array([[ 8,  9],
       [12, 13]]), array([[10, 11],
       [14, 15]])]


In [ ]:
import numpy as np

a = np.arange(16).reshape(4,4)

# Split into 2 rows and 2 columns in one go
blocks = [np.hsplit(row_block, 2) for row_block in np.vsplit(a, 2)]

print(blocks)

[[array([[0, 1],
       [4, 5]]), array([[2, 3],
       [6, 7]])], [array([[ 8,  9],
       [12, 13]]), array([[10, 11],
       [14, 15]])]]


In [50]:
a = np.arange(16).reshape(4,4)

# Split rows first
row_blocks = np.array_split(a, 2, axis=0)

# Then split each row block into columns
quadrants = [np.array_split(b, 2, axis=1) for b in row_blocks]

print(quadrants)


[[array([[0, 1],
       [4, 5]]), array([[2, 3],
       [6, 7]])], [array([[ 8,  9],
       [12, 13]]), array([[10, 11],
       [14, 15]])]]


In [ ]:
data = np.arange(24).reshape(12,2)
batches = data.reshape(4,3,2)

(4, 3, 2)


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [56]:
pixels = np.arange(64)  
image = pixels.reshape(8,8)
row_blocks = np.array_split(image, 2, axis=0)  
quadrants = [np.array_split(b, 2, axis=1) for b in row_blocks]

for q in quadrants:
    for block in q:
        print(block, "\n")


[[ 0  1  2  3]
 [ 8  9 10 11]
 [16 17 18 19]
 [24 25 26 27]] 

[[ 4  5  6  7]
 [12 13 14 15]
 [20 21 22 23]
 [28 29 30 31]] 

[[32 33 34 35]
 [40 41 42 43]
 [48 49 50 51]
 [56 57 58 59]] 

[[36 37 38 39]
 [44 45 46 47]
 [52 53 54 55]
 [60 61 62 63]] 

