In [1]:
import numpy as np
arr = np.array([1,2,3])
print(arr+5)

[6 7 8]


In [4]:
a = np.array([[1],[2],[3]])   # shape (3,1)
b = np.array([10,20,30]) 
print(a)    # shape (3,)
print(b)
print(a + b)

[[1]
 [2]
 [3]]
[10 20 30]
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [6]:
M = np.ones((3,3))
v = np.array([1,2,3])
print(M * v)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [8]:
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
row_mean= M.mean(axis=1,keepdims=True)
normalized= M - row_mean
print("Original:\n", M)
print("Row means:\n", row_mean)
print("Normalized:\n", normalized)

Original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Row means:
 [[2.]
 [5.]
 [8.]]
Normalized:
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
