In [3]:
import numpy as np
z= np.zeros((2,3))
o= np.ones((3,2))
print(z)
print(o)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
e= np.empty((3,3))
print(e)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [11]:
I= np.identity(4)
print(I)
I.shape

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


(4, 4)

In [12]:
r = np.random.rand(2,3)
print(r)

[[0.15099381 0.1933853  0.43771777]
 [0.84749895 0.01950871 0.01884418]]


In [16]:
print(np.random.randint(1,10,(3,3)))

[[4 3 4]
 [4 6 4]
 [7 7 5]]


In [33]:
a=np.ones((2,2))
print(a)
a[0,0].dtype

[[1. 1.]
 [1. 1.]]


dtype('float64')

In [37]:
f=np.empty((4,4))
print(f)
print(f)

[[0.00000000e+000 5.90678090e-315 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 2.12199579e-314]]
[[0.00000000e+000 5.90678090e-315 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 2.12199579e-314]]


In [57]:
g= np.empty((3,3))
print(g)

[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]


In [59]:
g.fill(5)
print(g)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [61]:
g= np.full((4,4),6)
print(g)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [67]:
I=np.identity(6)
I.fill(0)
print(I)
print(f"{I.shape},{I.ndim},{I.size}")

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
(6, 6),2,36


In [ ]:
a=np.empty((1000,1000),dtype=np.int32)
b=np.empty((1000,1000),dtype=np.int64)
print(a.nbytes)
print(b.nbytes)

4000000
8000000


In [70]:
a=np.array([[2,3],[4,5]])
b=np.identity(2)
print(f"{a} X {b} = {a*b}")
print(f"{a} X {b} = {a@b}")

[[2 3]
 [4 5]] X [[1. 0.]
 [0. 1.]] = [[2. 0.]
 [0. 5.]]
[[2 3]
 [4 5]] X [[1. 0.]
 [0. 1.]] = [[2. 3.]
 [4. 5.]]
