In [1]:
import numpy as np
arr = np.array([1,2,3])
print(arr+5)

[6 7 8]


In [2]:
a = np.array([[1],[2],[3]])   # shape (3,1)
b = np.array([10,20,30]) 
print(a)    # shape (3,)
print(b)
print(a + b)

[[1]
 [2]
 [3]]
[10 20 30]
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [3]:
M = np.ones((3,3))
v = np.array([1,2,3])
print(M * v)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [4]:
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
row_mean= M.mean(axis=1,keepdims=True)
normalized= M - row_mean
print("Original:\n", M)
print("Row means:\n", row_mean)
print("Normalized:\n", normalized)

Original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Row means:
 [[2.]
 [5.]
 [8.]]
Normalized:
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [5]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(M[0:2, 1:3]) 

[[2 3]
 [5 6]]


In [6]:
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
n=np.mean(M)
print(M[M>n])
print(M[M%2!=0])
print(M[M%3==0])

[6 7 8 9]
[1 3 5 7 9]
[3 6 9]


In [7]:
a= np.arange(12)
print(a.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]


In [9]:
print(np.hstack((a,b)))

[1 2 3 4 5 6]


In [10]:
a= np.arange(9).reshape(3,3)
print(np.hsplit(a,3))

[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]


In [11]:
print(np.vsplit(a, 3))

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]


In [12]:
arr = a.flatten()
print(arr)

[0 1 2 3 4 5 6 7 8]


In [13]:
r= arr.ravel()
r[0]= 99
r[3]= 10
print(arr)

[99  1  2 10  4  5  6  7  8]


In [14]:
a= np.array([1,2,3])
b= np.array([4,5,6])
print(np.vstack((a,b)))
print(np.shape(np.vstack((a,b))))

[[1 2 3]
 [4 5 6]]
(2, 3)


In [15]:
print(np.hstack((a,b)))

[1 2 3 4 5 6]


In [16]:
a = (np.arange(16)).reshape(4,4)
b=np.vsplit(a,2)
c= np.hsplit(b[0],2)
d=np.hsplit(b[1],2)
print(c,d)

[array([[0, 1],
       [4, 5]]), array([[2, 3],
       [6, 7]])] [array([[ 8,  9],
       [12, 13]]), array([[10, 11],
       [14, 15]])]


In [17]:
import numpy as np

a = np.arange(16).reshape(4,4)

# Split into 2 rows and 2 columns in one go
blocks = [np.hsplit(row_block, 2) for row_block in np.vsplit(a, 2)]

print(blocks)

[[array([[0, 1],
       [4, 5]]), array([[2, 3],
       [6, 7]])], [array([[ 8,  9],
       [12, 13]]), array([[10, 11],
       [14, 15]])]]


In [18]:
a = np.arange(16).reshape(4,4)

# Split rows first
row_blocks = np.array_split(a, 2, axis=0)

# Then split each row block into columns
quadrants = [np.array_split(b, 2, axis=1) for b in row_blocks]

print(quadrants)


[[array([[0, 1],
       [4, 5]]), array([[2, 3],
       [6, 7]])], [array([[ 8,  9],
       [12, 13]]), array([[10, 11],
       [14, 15]])]]


In [19]:
data = np.arange(24).reshape(12,2)
batches = data.reshape(4,3,2)

In [20]:
pixels = np.arange(64)  
image = pixels.reshape(8,8)
row_blocks = np.array_split(image, 2, axis=0)  
quadrants = [np.array_split(b, 2, axis=1) for b in row_blocks]

for q in quadrants:
    for block in q:
        print(block, "\n")


[[ 0  1  2  3]
 [ 8  9 10 11]
 [16 17 18 19]
 [24 25 26 27]] 

[[ 4  5  6  7]
 [12 13 14 15]
 [20 21 22 23]
 [28 29 30 31]] 

[[32 33 34 35]
 [40 41 42 43]
 [48 49 50 51]
 [56 57 58 59]] 

[[36 37 38 39]
 [44 45 46 47]
 [52 53 54 55]
 [60 61 62 63]] 



In [21]:
np.eye(3,5)
np.diag([1,2,3])
np.diag([1, 2, 3], 5)
a = np.array([[1, 2], [3, 4]])
np.diag(a)

array([1, 4])

In [22]:
np.vander(np.linspace(0, 2, 5), 2)

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [23]:
np.vander([1, 2, 3, 4], 3)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

In [24]:
np.zeros((2, 3),dtype=int)
np.zeros((2, 3, 2),dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [25]:
rng= np.random.default_rng()
rng.integers(low=0, high=10, size=(5,5))
rng.standard_normal(10)
rng.random()
from numpy.random import default_rng
default_rng(42).random((2,3))

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235]])

In [26]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [27]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = a.copy()
b += 1
print('a = ', a, 'b = ', b)

a =  [1 2 3 4] b =  [2 3 4 5]


In [28]:
import numpy as np
A = np.ones((2, 2))
B = np.eye(2, 2)
C = np.zeros((2, 2))
D = np.diag((-3, -4))
np.block([[A, B], [C, D]])

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])

In [29]:
np.genfromtxt("Numpy_6.csv", delimiter=",", usemask=True)

masked_array(
  data=[[1.0, 2.0, 3.0],
        [4.0, --, 6.0],
        [7.0, 8.0, 9.0]],
  mask=[[False, False, False],
        [False,  True, False],
        [False, False, False]],
  fill_value=1e+20)

In [30]:
np.genfromtxt("Numpy_6.csv", delimiter=",", filling_values=99,dtype=np.int32)

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]], dtype=int32)

In [31]:
np.genfromtxt("Numpy_6.csv", invalid_raise=False,delimiter=",") 

array([[ 1.,  2.,  3.],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.]])

In [32]:
np.load("Numpy_5_4.npz", allow_pickle=True)

NpzFile 'Numpy_5_4.npz' with keys: x, y

In [33]:
x=np.arange(10)
x.shape =(2,5)

In [34]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
rows = np.array([[0, 0],
                 [3, 3]], dtype=np.intp)
columns = np.array([[0, 2],
                    [0, 2]], dtype=np.intp)
x[rows, columns]

array([[ 0,  2],
       [ 9, 11]])

In [35]:
rows = np.array([0, 3], dtype=np.intp)
columns = np.array([0, 2], dtype=np.intp)
x[rows.reshape(2,1), columns]

array([[ 0,  2],
       [ 9, 11]])

In [36]:
x[np.ix_(rows,columns)]
# x[rows, columns]

array([[ 0,  2],
       [ 9, 11]])

In [37]:
x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])
x[~np.isnan(x)]

array([1., 2., 3.])

In [38]:
x = np.arange(35).reshape(5, 7)
b = x > 28
print(b)
b[:,:5]

[[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False  True  True  True  True  True  True]]


array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True]])

In [39]:
x = np.array([[0, 1], [1, 1], [2, 2]])
rowsum = x.sum(-1)
x[rowsum<=2,:]

array([[0, 1],
       [1, 1]])

In [40]:
x = np.ones((2,3,3,5))
print(x)
print(x.sum(axis=0))
print(x.sum(axis=1))
print(x.sum(axis=2))
print(x.sum(axis=3))

[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]]
[[[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]]
[[[3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]]

 [[3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]]]
[[[3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]]

 [[3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]]]
[[[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]]


In [41]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
print(x[(x.sum(axis=1))%2==0,:])
columns= [0,2]
# x[:,columns]
print(x[np.ix_(range(4),columns)])

[[ 3  4  5]
 [ 9 10 11]]
[[ 0  2]
 [ 3  5]
 [ 6  8]
 [ 9 11]]


In [42]:
rows=np.array([ 9, 10, 11])
rows = rows.nonzero()[0]
x[rows[:, np.newaxis]]

array([[[0, 1, 2]],

       [[3, 4, 5]],

       [[6, 7, 8]]])

In [43]:
x = np.arange(30).reshape(2, 3, 5)
x
b = np.array([[True, True, False], [False, True, True]])
x[b]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [44]:
y = np.arange(35).reshape(5,7)
y[np.array([0, 2, 4]), 1:3]

array([[ 1,  2],
       [15, 16],
       [29, 30]])

In [45]:
y[:, 1:3][np.array([0, 2, 4]), :]

array([[ 1,  2],
       [15, 16],
       [29, 30]])

In [46]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
x[1:2, 1:3]
x[1:2, [1, 2]]

array([[4, 5]])

In [53]:
x = np.arange(35).reshape(5, 7)
print(x)
b = x > 20
x[b[:, 5], 1:3]
x[[False, False, False, True, True], 1:3]

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


array([[22, 23],
       [29, 30]])

In [ ]:
import numpy as np

# Define a structured dtype
dt = np.dtype([('name', 'U10'), ('age', 'i4'), ('height', 'f4')])

# Create array
x = np.array([('Alice', 25, 5.5),
              ('Bob',   30, 6.0),
              ('Cara',  22, 5.7)], dtype=dt)

print(x['name'])   # ['Alice' 'Bob' 'Cara']
print(x['age'])    # [25 30 22]
print(x['height']) # [5.5 6.  5.7]
print(x[['name','age']])
dt = np.dtype([('coords', 'f4', (3,))])  # field with 3 numbers
x = np.array([([1,2,3],), ([4,5,6],)], dtype=dt)
print(x['coords'])
# [[1. 2. 3.]
#  [4. 5. 6.]]
print(x.dtype.names)   # ('coords',)

['Alice' 'Bob' 'Cara']
[25 30 22]
[5.5 6.  5.7]
[('Alice', 25) ('Bob', 30) ('Cara', 22)]
[[1. 2. 3.]
 [4. 5. 6.]]
('coords',)


In [60]:
x = np.zeros((2, 2), dtype=[('a',"i4"), ('b', np.float64, (3, 3))])
print(x)
x['a'].shape
x['a'].dtype
x['b'].shape
x['b'].dtype

[[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]
 [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]]


dtype('float64')

In [66]:
x = np.arange(6).reshape(2,3)
print(x[:,:])
print(x.flat[:])
print(x.flat[[0,3,4]])

# [[0 1 2]
#  [3 4 5]]

for val in x.flat:
    print(val, end=" ")
# 0 1 2 3 4 5

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
[0 3 4]
0 1 2 3 4 5 

In [68]:
x = np.arange(10)
x[2:7] = 1
print(x)

[0 1 1 1 1 1 1 7 8 9]


In [ ]:
x[2:7] = np.arange(5)
print(x)

[0 1 0 1 2 3 4 7 8 9]


In [72]:
x[1] = 1.2
print(x[1])
# x[1] = 1.2j  

1
