In [8]:
import numpy as np 

a= np.array([1,2,3,4])
print(a*3)

[ 3  6  9 12]


In [9]:
python_list = [1,2,3]
numpy_arry= np.array([1,2,3])
print(type(python_list))
print(type(numpy_arry))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
a= np.array([1,2,3])
b=2
print(a+b)

[3 4 5]


In [13]:
a= np.array(["namit","misty","Nikita","papa"])
b= "hero"
print(a+b)

['namithero' 'mistyhero' 'Nikitahero' 'papahero']


In [14]:
a= np.array([1,2,3])
b= np.array([4,5,6])
c=a*b
print(c)

[ 4 10 18]


In [ ]:
a= np.array([[1,2,3,4],[1,4,5,7],[8,7,9,10]])
print(a**2)
print9
print(a+5)

[[  1   4   9  16]
 [  1  16  25  49]
 [ 64  49  81 100]]
[[ 6  7  8  9]
 [ 6  9 10 12]
 [13 12 14 15]]


In [21]:
for i in range (1000000):
    i**2

KeyboardInterrupt: 

In [24]:
a= [1,2,3]
a.shape

AttributeError: 'list' object has no attribute 'shape'

In [32]:
a=np.array([[1,2,3,4],[1,2,5,7]])
print(a.shape)
a.dtype


(2, 4)


dtype('int64')

In [29]:
a=

SyntaxError: invalid syntax (62411553.py, line 1)

In [1]:
a=1
b=2
print(a+b)

3


In [4]:
import time
import numpy as np

N= 10_000_000
a= np.arange(N)

In [5]:
start= time.time()
result_loop =[]
for i in a:
    result_loop.append(i**2)
end = time.time()
print("python loop time",end-start,"s")

python loop time 1.5494215488433838 s


In [6]:
start= time.time()
result=a**2
end = time.time()
print("Numpy",end-start,"s")

Numpy 0.03543972969055176 s


In [8]:
print(np.arange(5,15))

[ 5  6  7  8  9 10 11 12 13 14]


In [12]:
print(np.arange(0,20,2))

[ 0  2  4  6  8 10 12 14 16 18]


In [16]:
print(np.arange(10))
print(np.linspace(0,9,5))

[0 1 2 3 4 5 6 7 8 9]
[0.   2.25 4.5  6.75 9.  ]
