In [2]:
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr[0])   
print(arr[2])   

10
30


In [3]:
print(arr[-1])
print(arr[-2])

40
30


In [4]:
arr= np.array([0,1,2,3,4,5])
print(arr[1:4])
print(arr[:3])
print(arr[3:])

[1 2 3]
[0 1 2]
[3 4 5]


In [5]:
print(arr[::2])
print(arr[1::2])

[0 2 4]
[1 3 5]


In [6]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(mat[0, 2])  
print(mat[1, :])   
print(mat[:, 1])   


3
[4 5 6]
[2 5 8]


In [9]:
print(mat[[0,2],[1,2]])

[2 9]


In [10]:
a= np.array([10,20,30,40,50])
print(f"{a[1]} , {a[3]}")

20 , 40


In [13]:
b=np.array([[11, 12, 13],
          [21, 22, 23],
          [31, 32, 33]])
print(b[1])
print(b[:,-1])

[21 22 23]
[13 23 33]


In [22]:
c= np.arange(1,17).reshape(4,4)
print(c[:,-1])
print(c[:,1])

[ 4  8 12 16]
[ 2  6 10 14]


In [24]:
arr= np.array([10, 20, 30, 40, 50])
mask = arr>25
print(mask)
print(arr[mask])

[False False  True  True  True]
[30 40 50]


In [27]:
arr = np.arange(1,11)
print(arr[(arr>3)&(arr<8)])
print(arr[(arr<4)|(arr>8)])

[4 5 6 7]
[ 1  2  3  9 10]


In [28]:
mat= np.array([[11, 12, 13],
                [21, 22, 23],
                [31, 32, 33]])

print(mat[mat > 20 ])

[21 22 23 31 32 33]


In [32]:
arr = np.arange(10)
print(arr)
mask = arr>5
print(arr[mask])
print(arr[[0,2,4]])

[0 1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[0 2 4]


In [33]:
mat = np.array([[1, 2, 3],
                [4, 5, 6]])

vec = np.array([10, 20, 30])

print(mat + vec)

[[11 22 33]
 [14 25 36]]


In [34]:
print(np.add(mat,10))
print(np.multiply(mat,5))
print(np.power(mat,3))

[[11 12 13]
 [14 15 16]]
[[ 5 10 15]
 [20 25 30]]
[[  1   8  27]
 [ 64 125 216]]


In [36]:
angle= np.array([0,np.pi/2 , np.pi])
print(np.sin(angle))
print(np.cos(angle))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [37]:
angle= np.array([0,np.pi/2 , np.pi])
print(np.round(np.sin(angle)).astype(int))
print(np.round(np.cos(angle).astype(int)))

[0 1 0]
[ 1  0 -1]


In [ ]:
a=np.array([0,np.pi/4,np.pi/2,np.pi])
b=np.power(np.sin(a),2)
c=np.power(np.cos(a),2)
print((b+c).astype(int)==1)

[ True  True  True  True]


In [49]:
print(np.round((np.tan([0,np.pi/6,np.pi/3])),2))

[0.   0.58 1.73]


In [50]:
np.round(np.exp([0,1,2]), 0)

array([1., 3., 7.])

In [54]:
student_dtype=np.dtype([
    ("name","U10"),
    ("age", "i4"),
    ("score", "f4")
])
students = np.array([
    ('Alice', 21, 88.5),
    ('Bob',   19, 92.0),
    ('Charlie', 22, 79.5)   
],dtype=student_dtype)
print(students)

[('Alice', 21, 88.5) ('Bob', 19, 92. ) ('Charlie', 22, 79.5)]


In [59]:
c= np.array([1,2,3],dtype=int)
d= np.array(["a","b","c"],dtype="U5")
print(c.dtype)
print(d.dtype)


int64
<U5
